services:
  - type: web
    name: projeto1-reclameaqui-dashboard
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: streamlit run dashboard/app.py --server.port $PORT --server.address 0.0.0.0
